apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: service # {"$kpt-set":"name"}
build:
  artifacts:
  - image: eu.gcr.io/tools-org-acme/service # {"$kpt-set":"app-image"}
    docker:
      dockerfile: Dockerfile
  - image: eu.gcr.io/tools-org-acme/service-flyway # {"$kpt-set":"flyway-image"}
    docker:
      dockerfile: flyway.Dockerfile
  - image: eu.gcr.io/tools-org-acme/service-doc # {"$kpt-set":"doc-image"}
    docker:
      dockerfile: redoc.Dockerfile
profiles:
- name: gcp
  activation:
  - kubeContext: .*gke.*
  deploy:
    kustomize:
    - "kustomize/gcp"
- name: local
  deploy:
    kustomize:
      paths:
      - "kustomize/local"
  activation:
  - kubeContext: (minikube|kind-.*|k3d-(.*))
  portForward:
  - resourceType: deployment
    resourceName: service # {"$kpt-set":"name"}
    port: 80
    localPort: 4200
