apiVersion: apps/v1
kind: Deployment
metadata:
  name: service # {"$kpt-set":"name"}
spec:
  template:
    spec:
      containers:
      - name: service # {"$kpt-set":"name"}
        env:
        - name: stage
          valueFrom:
            configMapKeyRef:
              key: stage
              name: application-properties
        - name: baseUrlPartyService
          valueFrom:
            configMapKeyRef:
              key: baseUrlPartyService
              name: application-properties
        - name: auth0_domain
          valueFrom:
            configMapKeyRef:
              key: auth0_domain
              name: application-properties
        - name: auth0_client_id
          valueFrom:
            configMapKeyRef:
              key: auth0_client_id
              name: application-properties
        - name: auth0_audience
          valueFrom:
            configMapKeyRef:
              key: auth0_audience
              name: application-properties
