apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../gcp
patchesStrategicMerge:
- virtualservice.yaml
configMapGenerator:
- name: application-properties
  behavior: merge
  files:
  - application.properties
