apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- redoc-deployment.yaml
- redoc-service.yaml
# patchesStrategicMerge does not support CRDs, so use patches
#  https://github.com/GoogleContainerTools/kpt/issues/506
#  https://github.com/kubernetes-sigs/kustomize/issues/742
patches:
- target:
    group: networking.istio.io
    version: v1beta1
    kind: VirtualService
    name: service # {"$kpt-set":"name"}
  path: add-docs-to-virtual-service.yaml
