apiVersion: v1
kind: Service
metadata:
  name: service-docs # {"$kpt-set":"service-docs"}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: service # {"$kpt-set":"name"}
    version: v1
    component: docs
