apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# patchesStrategicMerge does not support CRDs, so use patchesJSON6902
#  https://github.com/GoogleContainerTools/kpt/issues/506
#  https://github.com/kubernetes-sigs/kustomize/issues/742
patches:
- target:
    group: networking.istio.io
    version: v1beta1
    kind: VirtualService
    name: service # {"$kpt-set":"name"}
  path: add-cors-policy-to-virtual-service.yaml
- target:
    group: security.istio.io
    version: v1beta1
    kind: AuthorizationPolicy
    name: service # {"$kpt-set":"name"}
  path: add-preflight-to-auth-policy.yaml
