apiVersion: apps/v1
kind: Deployment
metadata:
  name: service # {"$kpt-set":"name"}
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: service # {"$kpt-set":"name"}
        image: eu.gcr.io/tools-org-acme/service # {"$kpt-set":"app-image"}
        imagePullPolicy: IfNotPresent
        env: []
        ports:
        - name: http
          containerPort: 8080 # {"$kpt-set":"app-container-port"}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness/health # {"$kpt-set":"liveness-check-path"}
            port: 8080 # {"$kpt-set":"app-container-port"}
        readinessProbe:
          httpGet:
            path: /readiness/health # {"$kpt-set":"readiness-check-path"}
            port: 8080 # {"$kpt-set":"app-container-port"}
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
