apiVersion: apps/v1
kind: Deployment
metadata:
  name: service # {"$kpt-set":"name"}
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: service # {"$kpt-set":"name"}
        image: eu.gcr.io/tools-org-acme/service # {"$kpt-set":"app-image"}
        imagePullPolicy: IfNotPresent
        env: []
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
