apiVersion: apps/v1
kind: Deployment
metadata:
  name: service # {"$kpt-set":"name"}
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: service # {"$kpt-set":"name"}
        image: eu.gcr.io/tools-org-acme/service # {"$kpt-set":"app-image"}
        imagePullPolicy: IfNotPresent
        env:
        - name: stage
          valueFrom:
            configMapKeyRef:
              key: stage
              name: application-properties
        - name: baseUrlPartyService
          valueFrom:
            configMapKeyRef:
              key: baseUrlPartyService
              name: application-properties
        - name: auth0_domain
          valueFrom:
            configMapKeyRef:
              key: auth0_domain
              name: application-properties
        - name: auth0_client_id
          valueFrom:
            configMapKeyRef:
              key: auth0_client_id
              name: application-properties
        - name: auth0_audience
          valueFrom:
            configMapKeyRef:
              key: auth0_audience
              name: application-properties
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
