apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: service # {"$kpt-set":"name"}
  version: v1
  component: api
resources:
- deployment.yaml
- service.yaml
images:
- name: eu.gcr.io/tools-org-acme/service # {"$kpt-set":"app-image"}
  newTag: 0.1.11
configMapGenerator:
- name: application-properties
  files:
  - application.properties
configurations:
- config.yaml
