apiVersion: apps/v1
kind: Deployment
metadata:
  name: service # {"$kpt-set":"name"}
spec:
  template:
    spec:
      containers:
      - name: service # {"$kpt-set":"name"}
        env:
        - name: DATABASE_DATABASE
          value: database-name
        - name: DATABASE_HOST
          value: localhost
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret # {"$kpt-set":"db-secret"}
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret # {"$kpt-set":"db-secret"}
              key: password
