name: Deploy feature branch to dev
on:
  push:
    branches:
    - feature/[0-9A-Za-z]+-?[0-9A-Za-z]*
    - next
env:
  SERVICE_NAME: service # {"$kpt-set":"name"}
  GKE_CLUSTER: gke1 # {"$kpt-set":"gke_cluster"}
  GCLOUD_ZONE: europe-west1 # {"$kpt-set":"gcloud_zone"}
  GCLOUD_APPLICATION_PROJECT: dev-org-acme # {"$kpt-set":"gcloud_application_project"}
  GCLOUD_GCR_PROJECT: tools-org-acme # {"$kpt-set":"gcloud_gcr_project"}
  KUBERNETES_DEPLOY_NAMESPACE: org-istio # {"$kpt-set":"gke_deploy_namespace"}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install Skaffold
      run: |
        curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        sudo install /tmp/skaffold /usr/local/bin/
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ env.GCLOUD_GCR_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - run: gcloud auth configure-docker
    - run: gcloud container clusters get-credentials $GKE_CLUSTER --zone=$GCLOUD_ZONE
        --project=$GCLOUD_APPLICATION_PROJECT
    - name: deploy application in k8s cluster
      run: CONTEXT=${GITHUB_REF##*/} skaffold run --namespace=$KUBERNETES_DEPLOY_NAMESPACE
    - name: run basic test
      run: helm test ${GITHUB_REF##*/}-$SERVICE_NAME --namespace=$KUBERNETES_DEPLOY_NAMESPACE
